### ISSUE TITLE
mkdir error: permission denied

### ISSUE THREAD

**Issue by chmaynard** [barrowclift/hacker-news-cleanser#2]
Not sure if this is a problem:
```
hacker-news-cleanser (master) $ admin/start.sh
Log directory cleaned
Starting Hacker News Cleanser...
mkdir: /var/lib/mongo: Permission denied
MongoDB started
Server started
All started successfully
```

I'm self-hosting on a Mac running macOS 10.14.6.

**Comment by chmaynard** [comment]
mongodb.log error:
```
{"t":{"$date":"2021-02-03T13:17:50.652-05:00"},"s":"E",  "c":"STORAGE",  "id":20568,   "ctx":"initandlisten","msg":"Error setting up listener","attr":{"error":{"code":9001,"codeName":"SocketException","errmsg":"Address already in use"}}}
```

**Comment by barrowclift** [comment]
Hi Craig!

The `start.sh` script starts both MongoDB and the Hacker News Cleanser, one right after the other.

What you're seeing at `mkdir: /var/lib/mongo: Permission denied` is a MongoDB failure to initialize the database at that directory due to a permissions issue.

To resolve, you can do either of the following:

* Set a different directory (one that does not require root write permissions, like at `~/developer/mongo`) to persist your Mongo database to by changing the `MONGO_DB` setting in `admin/init.sh`.
* *Or*, create_ the `/var/lib/mongo` directory manually with root permissions, then set the owner to yourself, like so: `sudo mkdir /var/lib/mongo ; sudo chown -R $(whoami) /var/lib/mongo`

I failed to detect this oversight on my own machine since I had already manually set up MongoDB for another service, so this snag wasn't called out in the instructions. To prevent this in the future, I'll remove the default value from the `init.sh` script and add a step in `INSTALL.md` clarifying to set a directory the user account has write permissions to.

Thanks for catching this!

**Comment by barrowclift** [comment]
While I'm confident this specific issue will be resolved with the steps above, if any other issues during setup reveal themselves please don't hesitate to open another Issue, I'll be happy to give them a look.

**Comment by chmaynard** [comment]
Thanks for the clarification. Any idea what is causing this fatal error reported in the mongodb log? (Happy to open up another issue if you prefer.)

    "Error setting up listener","attr":{"error":{"code":9001,"codeName":"SocketException","errmsg":"Address already in use"}}}

**Comment by barrowclift** [comment]
The error message `Address already in use` tells me you most likely have a Mongo process already running (either orphaned or healthy, unsure with just this log). You should stop any previously Mongo processes before trying to start it back up again.
